version: "3.8"
services:
  database:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "$POSTGRES_USER"
      POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
      POSTGRES_DB: "$POSTGRES_DB"
    volumes:
      - ./postgres/:/var/lib/posgresql/data
    networks:
      - ft_transcendence

  backend:
    restart: always
    image: backend-node
    build:
      context: ./
      dockerfile: Dockerfile.backend-node
    volumes:
      - ./backend/:/app
    ports:
      - "3001:3001"
      - "4343:4343"
    depends_on:
      - database
    links:
      - database
    command: sh -c 'npx prisma db push && npm install && npm run start'
    networks:
      - ft_transcendence

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.frontend-node
    restart: always
    ports:
      - "3000:3000"
    volumes:
        - ./frontend/:/app
    image: frontend-node
    networks:
      - ft_transcendence
    depends_on:
      - backend

networks:
  ft_transcendence:
    driver: bridge
